services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - DATABASE_URL=sqlite:///db.sqlite3
    command: python manage.py runserver 0.0.0.0:8000

  vite:
    build:
      context: .
      dockerfile: Dockerfile2
    ports:
      - "5173:5173"
    volumes:
      - ./react/src:/assets/react/src
    environment:
      - NODE_ENV=development
    command: npm run dev -- --host 0.0.0.0 --port 5173